import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <header className="fixed top-0 left-0 w-full flex items-center justify-around">
          <div>
            <Image
              src={"/images/next.png"}
              width={100}
              height={100}
              alt="next"
            ></Image>
            {/* <div className="font-bold p-3 ">Next World</div> */}
          </div>
          <div className="space-x-2">
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
          </div>
        </header>
        {children}
        <footer className=" fixed bottom-0 left-0 w-full flex justify-center bg-amber-50 text-black font-semibold uppercase">
          <div className="flex-1">copyright @ 2025</div>
          <div className="flex-1">
            This is a demo site and used for the perpose of just learning next
            js
          </div>
        </footer>
      </body>
    </html>
  );
}
