import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="font-bold text-center text-3xl">Next World</header>
        {children}
        <footer className="flex text-center mt-auto bg-gray-400 text-black font-bold text-xl">
          <div className="flex-1">copyright @ 2025</div>
          <div className="flex-1">
            This is a demo site and used for the perpose of just learning next
            js
          </div>
        </footer>
      </body>
    </html>
  );
}
